### ISSUE TITLE
Kompatiblitätsmodus

### ISSUE THREAD

**Issue by petersternwald** [rammpeter/Panorama#2]
Hallo Peter
wo finde ich denn den aktuellen Kompatiblitätsmodus der DB?
Hätte vermutet das er auf der "DBA Allgemein->Startseite zu finden ist, aber da sehe ich ihn nicht.
Abfragen kann man ihn mit: SELECT name, value FROM v$parameter WHERE name = 'compatible';
Könntest du den noch mit eingflegen?
Vielen Dank
Peter Ostermann

**Comment by rammpeter** [comment]
>> where to find compatibility mode?
Content of v$parameter is viewable at menu "DBA general" / "Oracle parameter".

In addition compatible value is also shown in start page now with version 2.9.70.

Thanks, Peter Ostermann for the hint.
